# Generated by Django 4.2 on 2023-04-05 19:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeatmapSet',
            fields=[
                ('beatmapset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=255)),
                ('artist_unicode', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('title_unicode', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=1000)),
                ('video', models.BooleanField(default=False)),
                ('storyboard', models.BooleanField(default=False)),
                ('bpm', models.FloatField(default=0)),
                ('approved', models.IntegerField(default=0)),
                ('approved_date', models.DateTimeField(default=None, null=True)),
                ('submit_date', models.DateTimeField(default=None, null=True)),
                ('last_update', models.DateTimeField(default=None, null=True)),
                ('display_title', models.CharField(max_length=255)),
                ('genre_id', models.IntegerField(default=0)),
                ('language_id', models.IntegerField(default=0)),
                ('favorite_count', models.IntegerField(default=0)),
                ('play_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Beatmap Set',
                'verbose_name_plural': 'Beatmap Sets',
                'db_table': 'collection_beatmapset',
            },
        ),
        migrations.CreateModel(
            name='Beatmap',
            fields=[
                ('beatmap_id', models.IntegerField(primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=255)),
                ('creator_id', models.IntegerField()),
                ('checksum', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=255)),
                ('total_length', models.IntegerField(default=0)),
                ('hit_length', models.IntegerField(default=0)),
                ('count_total', models.IntegerField(default=0)),
                ('count_normal', models.IntegerField(default=0)),
                ('count_slider', models.IntegerField(default=0)),
                ('count_spinner', models.IntegerField(default=0)),
                ('diff_drain', models.FloatField(default=0)),
                ('diff_size', models.FloatField(default=0)),
                ('diff_overall', models.FloatField(default=0)),
                ('diff_approach', models.FloatField(default=0)),
                ('play_mode', models.IntegerField(default=0)),
                ('approved', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('difficulty_rating', models.FloatField(default=0)),
                ('play_count', models.IntegerField(default=0)),
                ('pass_count', models.IntegerField(default=0)),
                ('bpm', models.FloatField(default=0)),
                ('beatmapset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.beatmapset')),
            ],
            options={
                'verbose_name': 'Beatmap',
                'verbose_name_plural': 'Beatmaps',
                'db_table': 'collection_beatmap',
            },
        ),
    ]
