# Generated by Django 4.2 on 2023-04-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_collection_collectionbeatmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='default_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='collectionbeatmap',
            unique_together={('collection', 'beatmap')},
        ),
    ]
