# Generated by Django 4.2 on 2023-04-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_collection_default_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmapset',
            name='card_picture_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='beatmapset',
            name='cover_picture_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='beatmapset',
            name='full_size_picture_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='beatmapset',
            name='list_picture_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='beatmapset',
            name='thumbnail_picture_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
