# Generated by Django 4.2 on 2023-04-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_beatmapset_card_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
