# Generated by Django 4.2 on 2023-04-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_collection_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
