# Generated by Django 4.2 on 2023-04-19 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_collection_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionBeatmapSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('beatmapset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.beatmapset')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection')),
            ],
            options={
                'verbose_name': 'Collection Beatmap Set',
                'verbose_name_plural': 'Collection Beatmap Sets',
                'db_table': 'collection_collectionbeatmapset',
                'unique_together': {('collection', 'beatmapset')},
            },
        ),
    ]
